name: qrcode
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^8.1.6 # permission
  image_picker: 0.8.4+1 # image picker
  logger: ^1.1.0  # logger
  flutter_bloc: ^7.3.0 # state management
  flutter_svg: ^0.22.0  #render image SVG
  carousel_slider: ^4.0.0 # image slider
  shimmer: ^2.0.0  # shimmer when wait loading data
  http: ^0.13.3
  intl: ^0.17.0
  flash: ^2.0.1 # snackbar
  get_it: ^7.2.0 # manager instance
  shared_preferences: ^2.0.7
  pin_code_fields: ^7.3.0
  flutter_html: ^2.1.5 #display context as html
  qr_code_scanner: ^0.6.1 # scan image qr
  webview_flutter: ^2.1.2 # load url in app
  flutter_launcher_icons: ^0.9.2
  device_info: ^2.0.3
  change_app_package_name: ^1.0.0
  persistent_bottom_nav_bar: ^4.0.2
  firebase_messaging: ^10.0.7
  flutter_local_notifications: ^8.2.0
  firebase_core: ^1.7.0
  rxdart: ^0.27.3
  cached_network_image: ^3.2.0
  lottie: ^1.2.1
  flutter_dotenv: ^5.0.2
  path_provider: ^2.0.8
  keyboard_dismisser: ^2.0.0
  community_material_icon: ^5.9.55
  formz: ^0.4.1
  equatable: ^2.0.3
  toggle_switch: ^1.3.0
  font_awesome_flutter: ^9.2.0
  double_back_to_close_app: ^2.1.0
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.0.17
  bubble_tab_indicator: ^0.1.6
  titled_navigation_bar: ^4.1.0
  card_swiper: ^1.0.4
  page_indicator: ^0.4.1
  smooth_page_indicator: ^1.0.0+2
  dropdown_below: ^1.0.2
  flutter_mobx: ^2.0.3+1
  nb_utils: ^4.4.10
  get: ^4.6.1
  android_intent: ^2.0.2
  dio: ^4.0.4
  json_annotation: ^4.4.0
  retrofit: ^3.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  retrofit_generator: ^3.0.0+2
  meta: ^1.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic